import React, { useState, useRef, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import './App.css';

// --- ICONS ---
const SendIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg>;
const SparkleIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="url(#brand-grad)"><defs><linearGradient id="brand-grad" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stopColor="#1b3544" /><stop offset="100%" stopColor="#6EB487" /></linearGradient></defs><path d="M12 22c4.97 0 9-4.03 9-9-4.97 0-9-4.03-9-9-4.97 0-9 4.03-9 9 0 4.97 4.03 9 9 9zm0-2c-3.87 0-7-3.13-7-7 0-3.87 3.13-7 7-7 3.87 0 7 3.13 7 7 0 3.87-3.13 7-7 7z"/></svg>;
const UserIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>;

function App() {
  const { keyword } = useParams();
  const navigate = useNavigate();
  
  const [topic, setTopic] = useState("");
  const [messages, setMessages] = useState([]); 
  const [loading, setLoading] = useState(false);
  const [view, setView] = useState("chat");
  const [finalBlog, setFinalBlog] = useState("");

  const textareaRef = useRef(null);
  const chatEndRef = useRef(null);
  const hasAutoGenerated = useRef(false);

  const OLLAMA_MODEL = "gemma3:4b";
  const OLLAMA_ENDPOINT = "http://localhost:11434/api/generate";

  useEffect(() => {
    if (keyword && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleSend(keyword);
    }
  }, [keyword]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleInput = (e) => {
    setTopic(e.target.value);
    e.target.style.height = 'auto';
    e.target.style.height = `${e.target.scrollHeight}px`;
  };

  const handlePublish = (htmlContent) => {
    setFinalBlog(htmlContent);
    setView("published");
  };

  const handleSend = async (overrideTopic = null) => {
    const topicToUse = overrideTopic || topic;
    if (!topicToUse.trim()) return;

    if (!overrideTopic) {
        navigate(`/${topicToUse.replace(/\s+/g, '-')}`);
    }

    setTopic(""); 
    if(textareaRef.current) textareaRef.current.style.height = 'auto'; 
    
    setMessages(prev => [...prev, { role: 'user', content: topicToUse.replace(/-/g, ' ') }]);
    setLoading(true);
    setMessages(prev => [...prev, { role: 'ai', content: '', isLoading: true }]);

    // --- UPDATED PROMPT WITH IMAGE GENERATION INSTRUCTIONS ---
    const promptText = `You are an expert technical blog writer. Write a detailed blog post about: "${topicToUse}".
    
    Structure instructions:
    1. Start with a Catchy Title (<h1>).
    2. Write an Introduction (<p>).
    3. AFTER the introduction, insert an AI Image using this exact format: <img src="https://image.pollinations.ai/prompt/DESCRIPTION_OF_THE_IMAGE_HERE" alt="image description" />. Replace DESCRIPTION_OF_THE_IMAGE_HERE with a short, relevant description of what the image should look like based on the blog topic.
    4. Write 3-4 detailed body sections with headings (<h2>) and paragraphs (<p>).
    5. Insert another relevant AI Image between two of the body sections using the same <img> url format.
    6. Write a Conclusion (<p>).

    IMPORTANT: Output raw HTML only. Do NOT use Markdown blocks.`;

    try {
      const response = await fetch(OLLAMA_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: OLLAMA_MODEL,
          prompt: promptText,
          stream: false,
          options: { temperature: 0.7, num_ctx: 4096 }
        }),
      });

      if (!response.ok) throw new Error("Ollama API Error");

      const result = await response.json();
      let aiText = result.response;
      aiText = aiText.replace(/```html/g, '').replace(/```/g, '');

      setMessages(prev => {
        const newMsgs = [...prev];
        newMsgs[newMsgs.length - 1] = { role: 'ai', content: aiText, isLoading: false };
        return newMsgs;
      });

    } catch (err) {
      setMessages(prev => {
        const newMsgs = [...prev];
        newMsgs[newMsgs.length - 1] = { role: 'ai', content: "Error: Is Ollama running?", isLoading: false, isError: true };
        return newMsgs;
      });
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  if (view === 'published') {
    return (
      <div className="blog-page-container fade-in scrollable-container">
        <nav className="blog-nav">
          <button className="nav-btn" onClick={() => setView('chat')}>← Editor</button>
          <div className="brand-logo" style={{color:'#e3e3e3'}}>LIVE<span style={{color:'#6EB487'}}>PREVIEW</span></div>
        </nav>
        <div className="centered-article-wrapper">
            <article className="blog-article">
            <div dangerouslySetInnerHTML={{ __html: finalBlog }} />
            </article>
        </div>
      </div>
    );
  }

  return (
    <div className="app-layout">
      <main className="main-content">
        <div className="top-bar">
          <div className="brand-logo">BLOGSMITH<span style={{color: '#6EB487'}}>.AI</span></div>
          <div className="user-profile"><div className="avatar-circle"></div></div>
        </div>

        {messages.length === 0 ? (
          <div className="welcome-container">
            <div className="greet-text">
              <span className="gradient-text">Hello, Creator</span>
              <span style={{color: '#444746'}}>Enter a URL keyword or type below.</span>
            </div>
          </div>
        ) : (
          <div className="chat-feed scrollable-container">
            {messages.map((msg, idx) => (
              <div key={idx} className={`message-wrapper ${msg.role}`}>
                {msg.role === 'user' && (
                  <div className="user-message">
                    <div className="msg-text">{msg.content}</div>
                    <div className="user-icon"><UserIcon /></div>
                  </div>
                )}
                {msg.role === 'ai' && (
                  <div className="ai-message-group">
                    <div className="ai-icon"><SparkleIcon /></div>
                    {msg.isLoading ? (
                      <div className="loading-bubble">
                        <div className="gemini-loader"></div>
                        <span>Writing & generating images for "{keyword || topic}"...</span>
                      </div>
                    ) : (
                      <div className="blog-card fade-in">
                        <div className="blog-card-header"><span className="badge">GENERATED POST + IMAGES</span></div>
                        {/* Added a wrapper class for image styling */}
                        <div className="blog-content with-images" dangerouslySetInnerHTML={{ __html: msg.content }} />
                        <div className="blog-card-footer">
                           <button className="card-action primary" onClick={() => handlePublish(msg.content)}>Publish</button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
            <div ref={chatEndRef} />
          </div>
        )}

        <div className="input-area">
          <div className="input-container">
            <textarea
              ref={textareaRef}
              placeholder="Enter a topic..."
              rows={1}
              value={topic}
              onChange={handleInput}
              onKeyDown={handleKeyDown}
            />
            <button className={`submit-btn ${topic.trim() ? 'has-text' : ''}`} onClick={() => handleSend()}>
              <SendIcon />
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;